'use strict';
document.documentElement.classList.add('js');
const menu=document.querySelector('.menu-toggle'),nav=document.getElementById('main-nav');
if(menu&&nav){menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus()}})}
function tabs(selector,onChange){const buttons=[...document.querySelectorAll(selector)];function select(button,focus=false){buttons.forEach(item=>{const active=item===button;item.setAttribute('aria-selected',String(active));item.tabIndex=active?0:-1});onChange(button);if(focus)button.focus()}buttons.forEach((button,index)=>{button.addEventListener('click',()=>select(button));button.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight'||e.key==='ArrowDown')next=(index+1)%buttons.length;if(e.key==='ArrowLeft'||e.key==='ArrowUp')next=(index+buttons.length-1)%buttons.length;if(e.key==='Home')next=0;if(e.key==='End')next=buttons.length-1;if(next!==undefined){e.preventDefault();select(buttons[next],true)}})});return{buttons,select}}
const featureContent=[['Capture your perspective.','A 13 MP camera lets you save the view in front of you. Take photos and record video while keeping your phone tucked away.','Press the right button once for a photo, twice to start a video.'],['Your soundtrack. Your surroundings.','Listen to music and take Bluetooth calls through open-ear speakers built into the frame.','Tap the right touch strip to play or pause. Slide to adjust the volume.'],['Ask a little more.','Get conversational assistance, ask about a photo, and explore supported translation modes through the connected companion app.','Press the left button once to activate AI. App, phone connection and supported services are required.'],['A touch of simplicity.','Use the frame’s buttons and touch strip to capture, listen and stay connected. Familiar actions, right at your fingertips.','Hold the right button for three seconds to power on or off. See the English guide for all controls.']];
const featureTabs=tabs('[data-feature]',button=>{const index=Number(button.dataset.feature),content=featureContent[index];document.getElementById('feature-title').textContent=content[0];document.getElementById('feature-copy').textContent=content[1];document.getElementById('feature-detail').textContent=content[2];document.querySelector('.feature-index').textContent=`0${index+1} / 04`;document.getElementById('feature-panel').setAttribute('aria-labelledby',button.id);document.getElementById('ai-connection').hidden=index!==2;document.querySelectorAll('[data-hardware]').forEach(control=>control.setAttribute('aria-pressed',String(Number(control.dataset.hardware)===index)));const marker=index===0?'camera':index===3?'controls':'';document.querySelectorAll('[data-marker]').forEach(item=>item.classList.toggle('active',item.dataset.marker===marker))});
document.querySelectorAll('[data-hardware]').forEach(control=>control.addEventListener('click',()=>{const button=featureTabs.buttons.find(item=>item.dataset.feature===control.dataset.hardware);if(button)featureTabs.select(button,true)}));
const lifeContent={travel:{label:'TRAVEL',title:'Bring the moments home.',copy:'Capture the places and details you want to remember, with supported connected translation when you need it.',desktop:'assets/lifestyle-travel.webp',mobile:'assets/lifestyle-travel-mobile.webp',alt:'Illustrative travel scene',cta:'Explore APEX for travel'},outdoors:{label:'OUTDOORS',title:'Keep the view.',copy:'Capture the scenery ahead while keeping your hands free and your attention on the moment.',desktop:'assets/lifestyle-outdoors.webp',mobile:'assets/lifestyle-outdoors-mobile.webp',alt:'Illustrative outdoor scenery',cta:'Explore APEX outdoors'},everyday:{label:'EVERYDAY',title:'Stay connected.',copy:'Enjoy open-ear music, take Bluetooth calls and reach connected assistance throughout your day.',desktop:'assets/lifestyle-everyday.webp',mobile:'assets/lifestyle-everyday-mobile.webp',alt:'Illustrative everyday scene',cta:'Explore APEX every day'}};
let lifeRequest=0;
const initialLifeImage=document.getElementById('life-image');
if(initialLifeImage){
  initialLifeImage.addEventListener('error',()=>{
    const media=initialLifeImage.closest('.life-media');
    const status=document.getElementById('life-image-status');
    initialLifeImage.alt='';
    media.classList.remove('loading');
    media.classList.add('failed');
    status.hidden=false;
  });
}
tabs('[data-life]',button=>{const item=lifeContent[button.dataset.life],request=++lifeRequest,panel=document.getElementById('life-panel'),media=panel.querySelector('.life-media'),image=document.getElementById('life-image'),source=media.querySelector('source'),status=document.getElementById('life-image-status');document.getElementById('life-label').textContent=item.label;document.getElementById('life-title').textContent=item.title;document.getElementById('life-copy').textContent=item.copy;panel.setAttribute('aria-labelledby',button.id);panel.querySelector('a').textContent=item.cta;media.classList.add('loading');media.classList.remove('failed');status.hidden=true;const preload=new Image(),narrow=matchMedia('(max-width: 760px)').matches;preload.onload=()=>{if(request!==lifeRequest)return;source.srcset=item.mobile;image.src=item.desktop;image.alt=item.alt;media.classList.remove('loading')};preload.onerror=()=>{if(request!==lifeRequest)return;source.srcset='';image.removeAttribute('src');image.alt='';media.classList.remove('loading');media.classList.add('failed');status.hidden=false};preload.src=narrow?item.mobile:item.desktop});
const modelSelect=document.getElementById('order-model'),peso=value=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',minimumFractionDigits:2}).format(value);
if(modelSelect){const prices={APEX:5995,NOVA:5995,NEO:4995},update=()=>{const price=prices[modelSelect.value];document.getElementById('order-total').textContent=peso(price).replace('.00','');document.getElementById('order-deposit').textContent=peso(price/2);document.getElementById('order-balance').textContent=peso(price/2);document.getElementById('copy-status').textContent=''};modelSelect.addEventListener('change',update);document.getElementById('copy-order').addEventListener('click',async()=>{const price=prices[modelSelect.value],message=`Hi KTECH! I’d like to preorder ${modelSelect.value} at ${peso(price)}. Please confirm availability, payment details, included accessories, warranty terms and delivery fees. I understand the 50% down payment is ${peso(price/2)}, with the balance due before delivery.`,status=document.getElementById('copy-status');try{await navigator.clipboard.writeText(message);status.textContent='Copied. Open Instagram and paste your message.'}catch{status.textContent=message}});update()}
document.querySelectorAll('[data-order-model]').forEach(link=>link.addEventListener('click',()=>{if(!modelSelect)return;modelSelect.value=link.dataset.orderModel;modelSelect.dispatchEvent(new Event('change'))}));
